import { FLOW_TYPES } from '../../config/constants'
import type { Queryable } from '../../core/types'
import { getCourse } from '../catalog/queries'
import { saveFlowSession } from '../user/state'
export async function beginEnrollment(db:Queryable, input:{ userId:string; telegramId:number; courseId:string }) { const result = await db.query<{ id:string }>(`INSERT INTO course_enrollments (user_id, telegram_id, course_id, status, current_step, created_at, updated_at) VALUES ($1,$2,$3,'in_progress','full_name',NOW(),NOW()) ON CONFLICT ON CONSTRAINT uniq_active_enrollment_per_user DO UPDATE SET course_id=EXCLUDED.course_id, updated_at=NOW() RETURNING id`, [input.userId, input.telegramId, input.courseId]); const id = result.rows[0].id; await saveFlowSession(db, { userId:input.userId, telegramId:input.telegramId, flowType:FLOW_TYPES.COURSE, step:'full_name', payload:{ enrollmentId:id, courseId:input.courseId } }); return id }
export async function saveEnrollmentAnswer(db:Queryable, input:{ enrollmentId:string; fieldKey:string; fieldValue:string; nextStep?:string|null }): Promise<void> { await db.tx!(async client => { await client.query(`INSERT INTO enrollment_answers (enrollment_id, field_key, field_value, field_type, updated_at) VALUES ($1,$2,$3,'text',NOW()) ON CONFLICT (enrollment_id, field_key) DO UPDATE SET field_value=EXCLUDED.field_value, updated_at=NOW()`, [input.enrollmentId, input.fieldKey, input.fieldValue]); await client.query(`UPDATE course_enrollments SET current_step=$2, updated_at=NOW() WHERE id=$1`, [input.enrollmentId, input.nextStep ?? null]) }) }
export async function submitEnrollment(db:Queryable, enrollmentId:string): Promise<boolean> { const result = await db.query(`UPDATE course_enrollments SET status='submitted', submitted_at=NOW(), current_step=NULL, updated_at=NOW() WHERE id=$1 AND status='in_progress'`, [enrollmentId]); return (result.rowCount ?? 0) > 0 }
export async function cancelEnrollment(db:Queryable, telegramId:number, enrollmentId:string): Promise<void> { await db.tx!(async client => { await client.query(`UPDATE course_enrollments SET status='cancelled', current_step=NULL, updated_at=NOW() WHERE id=$1 AND status='in_progress'`, [enrollmentId]); await client.query(`DELETE FROM flow_sessions WHERE telegram_id=$1`, [telegramId]) }) }
export async function getCourseTitle(db:Queryable, courseId:string): Promise<string> { return (await getCourse(db, courseId))?.title ?? '—' }
export async function loadEnrollmentSummary(db:Queryable, enrollmentId:string): Promise<{ courseTitle:string; answers:Array<{ fieldKey:string; fieldValue:string }>; telegramId:number }|null> { const enrollment = await db.query<{ telegramId:number; courseTitle:string }>(`SELECT e.telegram_id AS "telegramId", c.title AS "courseTitle" FROM course_enrollments e JOIN courses c ON c.id=e.course_id WHERE e.id=$1 LIMIT 1`, [enrollmentId]); const hit=enrollment.rows[0]; if(!hit) return null; const answers = await db.query<{ fieldKey:string; fieldValue:string }>(`SELECT field_key AS "fieldKey", field_value AS "fieldValue" FROM enrollment_answers WHERE enrollment_id=$1 ORDER BY created_at ASC`, [enrollmentId]); return { courseTitle:hit.courseTitle, answers:answers.rows, telegramId:hit.telegramId } }
export async function reviewEnrollment(db:Queryable, input:{ enrollmentId:string; adminTelegramId:number; action:'approved'|'rejected' }): Promise<{ telegramId:number }|null> { const result = await db.query<{ telegramId:number }>(`UPDATE course_enrollments SET status=$2, reviewed_at=NOW(), reviewed_by=$3, updated_at=NOW() WHERE id=$1 AND status='submitted' RETURNING telegram_id AS "telegramId"`, [input.enrollmentId, input.action, input.adminTelegramId]); return result.rows[0] ?? null }
