import { InlineKeyboard } from 'grammy'
import { getEnv } from '../../config/env'
import type { AppContext, Lang, Queryable } from '../../core/types'
import { t } from '../../core/i18n'
import { loadApplicationSummary, reviewApplication } from '../application/service'
import { loadEnrollmentSummary, reviewEnrollment } from '../course/service'
import { escapeMarkdown } from '../../utils/markdown'
export function isAdmin(telegramId?:number): boolean { const env=getEnv(); return Boolean(telegramId && env.adminIds.includes(telegramId)) }
export function buildAdminActions(prefix:'AA'|'CE', entityId:string, lang:Lang){ return new InlineKeyboard().text(t(lang,'approve'), `${prefix}|APPROVE|${entityId}`).text(t(lang,'reject'), `${prefix}|REJECT|${entityId}`).row().text(t(lang,'review'), `${prefix}|REVIEW|${entityId}`) }
export async function notifyAdminsAboutApplication(ctx:AppContext, db:Queryable, applicationId:string, lang:Lang){ const env=getEnv(); const summary=await loadApplicationSummary(db, applicationId); if(!summary) return; const text=[`🆕 *${lang==='ru' ? 'Новая заявка' : 'Yangi ariza'}*`,`📌 *${escapeMarkdown(summary.vacancyTitle)}*`,...summary.answers.map(item => `• *${escapeMarkdown(item.fieldKey)}*: ${escapeMarkdown(item.fieldValue)}`)].join('\n'); for(const adminId of env.adminIds){ if(summary.photoUrl) await ctx.api.sendPhoto(adminId, summary.photoUrl, { caption:text, parse_mode:'Markdown', reply_markup:buildAdminActions('AA', applicationId, lang) }).catch(() => undefined); else await ctx.api.sendMessage(adminId, text, { parse_mode:'Markdown', reply_markup:buildAdminActions('AA', applicationId, lang) }).catch(() => undefined) } }
export async function notifyAdminsAboutEnrollment(ctx:AppContext, db:Queryable, enrollmentId:string, lang:Lang){ const env=getEnv(); const summary=await loadEnrollmentSummary(db, enrollmentId); if(!summary) return; const text=[`🆕 *${lang==='ru' ? 'Новая запись на курс' : 'Yangi kurs so‘rovi'}*`,`📚 *${escapeMarkdown(summary.courseTitle)}*`,...summary.answers.map(item => `• *${escapeMarkdown(item.fieldKey)}*: ${escapeMarkdown(item.fieldValue)}`)].join('\n'); for(const adminId of env.adminIds){ await ctx.api.sendMessage(adminId, text, { parse_mode:'Markdown', reply_markup:buildAdminActions('CE', enrollmentId, lang) }).catch(() => undefined) } }
export async function handleAdminDecision(ctx:AppContext, db:Queryable, namespace:'AA'|'CE', action:string, entityId:string, lang:Lang){ if(!ctx.from?.id || !isAdmin(ctx.from.id)){ await ctx.answerCallbackQuery({ text:t(lang,'adminOnly') }).catch(() => undefined); return } if(namespace === 'AA'){ const reviewed=await reviewApplication(db, { applicationId:entityId, adminTelegramId:ctx.from.id, action: action==='APPROVE' ? 'approved' : 'rejected' }); if(!reviewed){ await ctx.answerCallbackQuery({ text:t(lang,'alreadyReviewed') }).catch(() => undefined); return } await ctx.reply(action==='APPROVE' ? t(lang,'approved') : t(lang,'rejected')).catch(() => undefined); await ctx.api.sendMessage(reviewed.telegramId, action==='APPROVE' ? t(lang,'approved') : t(lang,'rejected')).catch(() => undefined); return } const reviewed=await reviewEnrollment(db, { enrollmentId:entityId, adminTelegramId:ctx.from.id, action: action==='APPROVE' ? 'approved' : 'rejected' }); if(!reviewed){ await ctx.answerCallbackQuery({ text:t(lang,'alreadyReviewed') }).catch(() => undefined); return } await ctx.reply(action==='APPROVE' ? t(lang,'approved') : t(lang,'rejected')).catch(() => undefined); await ctx.api.sendMessage(reviewed.telegramId, action==='APPROVE' ? t(lang,'approved') : t(lang,'rejected')).catch(() => undefined) }
