import { FLOW_TYPES } from '../../config/constants'
import type { Queryable } from '../../core/types'
import { getVacancyQuestions, getVacancy } from '../catalog/queries'
import { saveFlowSession } from '../user/state'
export async function beginApplication(db:Queryable, input:{ userId:string; telegramId:number; vacancyId:string }) { const result = await db.query<{ id:string }>(`INSERT INTO applications (user_id, telegram_id, vacancy_id, status, current_step, created_at, updated_at) VALUES ($1,$2,$3,'in_progress','full_name',NOW(),NOW()) ON CONFLICT ON CONSTRAINT uniq_active_application_per_user DO UPDATE SET vacancy_id=EXCLUDED.vacancy_id, updated_at=NOW() RETURNING id`, [input.userId, input.telegramId, input.vacancyId]); const id = result.rows[0].id; await saveFlowSession(db, { userId:input.userId, telegramId:input.telegramId, flowType:FLOW_TYPES.APPLICATION, step:'question', payload:{ applicationId:id, vacancyId:input.vacancyId, questionIndex:0 } }); return id }
export async function loadApplicationQuestions(db:Queryable, vacancyId:string){ return getVacancyQuestions(db, vacancyId) }
export async function saveApplicationAnswer(db:Queryable, input:{ applicationId:string; fieldKey:string; fieldValue:string; fieldType:string; nextStep?:string|null }): Promise<void> { await db.tx!(async client => { await client.query(`INSERT INTO application_answers (application_id, field_key, field_value, field_type, updated_at) VALUES ($1,$2,$3,$4,NOW()) ON CONFLICT (application_id, field_key) DO UPDATE SET field_value=EXCLUDED.field_value, field_type=EXCLUDED.field_type, updated_at=NOW()`, [input.applicationId, input.fieldKey, input.fieldValue, input.fieldType]); await client.query(`UPDATE applications SET current_step=$2, updated_at=NOW() WHERE id=$1`, [input.applicationId, input.nextStep ?? null]) }) }
export async function saveApplicationFile(db:Queryable, input:{ applicationId:string; fileRole:string; telegramFileId:string; cloudinaryUrl?:string|null; cloudinaryPublicId?:string|null }): Promise<void> { await db.query(`INSERT INTO application_files (application_id, file_role, telegram_file_id, cloudinary_url, cloudinary_public_id, file_kind) VALUES ($1,$2,$3,$4,$5,'telegram') ON CONFLICT (application_id, file_role) DO UPDATE SET telegram_file_id=EXCLUDED.telegram_file_id, cloudinary_url=EXCLUDED.cloudinary_url, cloudinary_public_id=EXCLUDED.cloudinary_public_id`, [input.applicationId, input.fileRole, input.telegramFileId, input.cloudinaryUrl ?? null, input.cloudinaryPublicId ?? null]) }
export async function submitApplication(db:Queryable, applicationId:string): Promise<boolean> { const result = await db.query(`UPDATE applications SET status='submitted', submitted_at=NOW(), updated_at=NOW(), current_step=NULL WHERE id=$1 AND status='in_progress'`, [applicationId]); return (result.rowCount ?? 0) > 0 }
export async function cancelApplication(db:Queryable, telegramId:number, applicationId:string): Promise<void> { await db.tx!(async client => { await client.query(`UPDATE applications SET status='cancelled', updated_at=NOW(), current_step=NULL WHERE id=$1 AND status='in_progress'`, [applicationId]); await client.query(`DELETE FROM flow_sessions WHERE telegram_id=$1`, [telegramId]) }) }
export async function getApplicationResumeCard(db:Queryable, applicationId:string): Promise<{ title:string; status:string }|null> { const result = await db.query<{ title:string; status:string }>(`SELECT COALESCE(v.title, '—') AS title, a.status FROM applications a LEFT JOIN vacancies v ON v.id=a.vacancy_id WHERE a.id=$1 LIMIT 1`, [applicationId]); return result.rows[0] ?? null }
export async function getVacancyTitle(db:Queryable, vacancyId:string): Promise<string> { return (await getVacancy(db, vacancyId))?.title ?? '—' }
export async function loadApplicationSummary(db:Queryable, applicationId:string): Promise<{ vacancyTitle:string; answers:Array<{ fieldKey:string; fieldValue:string }>; photoUrl:string|null; telegramId:number }|null> { const application = await db.query<{ telegramId:number; vacancyTitle:string }>(`SELECT a.telegram_id AS "telegramId", COALESCE(v.title, '—') AS "vacancyTitle" FROM applications a LEFT JOIN vacancies v ON v.id=a.vacancy_id WHERE a.id=$1 LIMIT 1`, [applicationId]); const hit=application.rows[0]; if(!hit) return null; const answers = await db.query<{ fieldKey:string; fieldValue:string }>(`SELECT field_key AS "fieldKey", field_value AS "fieldValue" FROM application_answers WHERE application_id=$1 ORDER BY created_at ASC`, [applicationId]); const photo = await db.query<{ url:string|null }>(`SELECT COALESCE(cloudinary_url, telegram_file_id) AS url FROM application_files WHERE application_id=$1 AND file_role='photo' LIMIT 1`, [applicationId]); return { vacancyTitle:hit.vacancyTitle, answers:answers.rows, photoUrl:photo.rows[0]?.url ?? null, telegramId:hit.telegramId } }
export async function reviewApplication(db:Queryable, input:{ applicationId:string; adminTelegramId:number; action:'approved'|'rejected' }): Promise<{ telegramId:number }|null> { const result = await db.query<{ telegramId:number }>(`UPDATE applications SET status=$2, reviewed_at=NOW(), reviewed_by=$3, updated_at=NOW() WHERE id=$1 AND status='submitted' RETURNING telegram_id AS "telegramId"`, [input.applicationId, input.action, input.adminTelegramId]); return result.rows[0] ?? null }
